/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocasEDevolucoesRouteImport } from './routes/trocas-e-devolucoes'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ColecaoRouteImport } from './routes/colecao'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutosIndexRouteImport } from './routes/produtos.index'
import { Route as PedidosIndexRouteImport } from './routes/pedidos.index'
import { Route as MarketingIndexRouteImport } from './routes/marketing.index'
import { Route as EstoqueIndexRouteImport } from './routes/estoque.index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as CategoriasIndexRouteImport } from './routes/categorias.index'
import { Route as ProdutosNovoRouteImport } from './routes/produtos.novo'
import { Route as ProdutoHandleRouteImport } from './routes/produto.$handle'
import { Route as PedidosIdRouteImport } from './routes/pedidos.$id'
import { Route as EstoqueHistoricoRouteImport } from './routes/estoque.historico'
import { Route as CategoriasNovoRouteImport } from './routes/categorias.novo'
import { Route as ProdutosIdEditarRouteImport } from './routes/produtos.$id.editar'
import { Route as CategoriasIdEditarRouteImport } from './routes/categorias.$id.editar'

const TrocasEDevolucoesRoute = TrocasEDevolucoesRouteImport.update({
  id: '/trocas-e-devolucoes',
  path: '/trocas-e-devolucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecaoRoute = ColecaoRouteImport.update({
  id: '/colecao',
  path: '/colecao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIndexRoute = PedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/marketing/',
  path: '/marketing/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/marketing/',
  path: '/marketing/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueIndexRoute = EstoqueIndexRouteImport.update({
  id: '/estoque/',
  path: '/estoque/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasIndexRoute = CategoriasIndexRouteImport.update({
  id: '/categorias/',
  path: '/categorias/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosNovoRoute = ProdutosNovoRouteImport.update({
  id: '/produtos/novo',
  path: '/produtos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoHandleRoute = ProdutoHandleRouteImport.update({
  id: '/produto/$handle',
  path: '/produto/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIdRoute = PedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueHistoricoRoute = EstoqueHistoricoRouteImport.update({
  id: '/estoque/historico',
  path: '/estoque/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasNovoRoute = CategoriasNovoRouteImport.update({
  id: '/categorias/novo',
  path: '/categorias/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIdEditarRoute = ProdutosIdEditarRouteImport.update({
  id: '/produtos/$id/editar',
  path: '/produtos/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasIdEditarRoute = CategoriasIdEditarRouteImport.update({
  id: '/categorias/$id/editar',
  path: '/categorias/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/colecao': typeof ColecaoRoute
  '/dashboard': typeof DashboardRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/trocas-e-devolucoes': typeof TrocasEDevolucoesRoute
  '/categorias/novo': typeof CategoriasNovoRoute
  '/estoque/historico': typeof EstoqueHistoricoRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/produto/$handle': typeof ProdutoHandleRoute
  '/produtos/novo': typeof ProdutosNovoRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/estoque/': typeof EstoqueIndexRoute
  '/marketing/': typeof MarketingIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/categorias/$id/editar': typeof CategoriasIdEditarRoute
  '/produtos/$id/editar': typeof ProdutosIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/colecao': typeof ColecaoRoute
  '/dashboard': typeof DashboardRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/trocas-e-devolucoes': typeof TrocasEDevolucoesRoute
  '/categorias/novo': typeof CategoriasNovoRoute
  '/estoque/historico': typeof EstoqueHistoricoRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/produto/$handle': typeof ProdutoHandleRoute
  '/produtos/novo': typeof ProdutosNovoRoute
  '/categorias': typeof CategoriasIndexRoute
  '/clientes': typeof ClientesIndexRoute
  '/estoque': typeof EstoqueIndexRoute
  '/marketing': typeof MarketingIndexRoute
  '/pedidos': typeof PedidosIndexRoute
  '/produtos': typeof ProdutosIndexRoute
  '/categorias/$id/editar': typeof CategoriasIdEditarRoute
  '/produtos/$id/editar': typeof ProdutosIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/colecao': typeof ColecaoRoute
  '/dashboard': typeof DashboardRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/trocas-e-devolucoes': typeof TrocasEDevolucoesRoute
  '/categorias/novo': typeof CategoriasNovoRoute
  '/estoque/historico': typeof EstoqueHistoricoRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/produto/$handle': typeof ProdutoHandleRoute
  '/produtos/novo': typeof ProdutosNovoRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/estoque/': typeof EstoqueIndexRoute
  '/marketing/': typeof MarketingIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/categorias/$id/editar': typeof CategoriasIdEditarRoute
  '/produtos/$id/editar': typeof ProdutosIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/colecao'
    | '/dashboard'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/trocas-e-devolucoes'
    | '/categorias/novo'
    | '/estoque/historico'
    | '/pedidos/$id'
    | '/produto/$handle'
    | '/produtos/novo'
    | '/categorias/'
    | '/clientes/'
    | '/estoque/'
    | '/marketing/'
    | '/pedidos/'
    | '/produtos/'
    | '/categorias/$id/editar'
    | '/produtos/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/colecao'
    | '/dashboard'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/trocas-e-devolucoes'
    | '/categorias/novo'
    | '/estoque/historico'
    | '/pedidos/$id'
    | '/produto/$handle'
    | '/produtos/novo'
    | '/categorias'
    | '/clientes'
    | '/estoque'
    | '/marketing'
    | '/pedidos'
    | '/produtos'
    | '/categorias/$id/editar'
    | '/produtos/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/colecao'
    | '/dashboard'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/trocas-e-devolucoes'
    | '/categorias/novo'
    | '/estoque/historico'
    | '/pedidos/$id'
    | '/produto/$handle'
    | '/produtos/novo'
    | '/categorias/'
    | '/clientes/'
    | '/estoque/'
    | '/marketing/'
    | '/pedidos/'
    | '/produtos/'
    | '/categorias/$id/editar'
    | '/produtos/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ColecaoRoute: typeof ColecaoRoute
  DashboardRoute: typeof DashboardRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  TrocasEDevolucoesRoute: typeof TrocasEDevolucoesRoute
  CategoriasNovoRoute: typeof CategoriasNovoRoute
  EstoqueHistoricoRoute: typeof EstoqueHistoricoRoute
  PedidosIdRoute: typeof PedidosIdRoute
  ProdutoHandleRoute: typeof ProdutoHandleRoute
  ProdutosNovoRoute: typeof ProdutosNovoRoute
  CategoriasIndexRoute: typeof CategoriasIndexRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  EstoqueIndexRoute: typeof EstoqueIndexRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  PedidosIndexRoute: typeof PedidosIndexRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
  CategoriasIdEditarRoute: typeof CategoriasIdEditarRoute
  ProdutosIdEditarRoute: typeof ProdutosIdEditarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trocas-e-devolucoes': {
      id: '/trocas-e-devolucoes'
      path: '/trocas-e-devolucoes'
      fullPath: '/trocas-e-devolucoes'
      preLoaderRoute: typeof TrocasEDevolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecao': {
      id: '/colecao'
      path: '/colecao'
      fullPath: '/colecao'
      preLoaderRoute: typeof ColecaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/': {
      id: '/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof PedidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/': {
      id: '/marketing/'
      path: '/marketing'
      fullPath: '/marketing/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque/': {
      id: '/estoque/'
      path: '/estoque'
      fullPath: '/estoque/'
      preLoaderRoute: typeof EstoqueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/': {
      id: '/categorias/'
      path: '/categorias'
      fullPath: '/categorias/'
      preLoaderRoute: typeof CategoriasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/': {
      id: '/marketing/'
      path: '/marketing'
      fullPath: '/marketing/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/novo': {
      id: '/produtos/novo'
      path: '/produtos/novo'
      fullPath: '/produtos/novo'
      preLoaderRoute: typeof ProdutosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$handle': {
      id: '/produto/$handle'
      path: '/produto/$handle'
      fullPath: '/produto/$handle'
      preLoaderRoute: typeof ProdutoHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/$id': {
      id: '/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof PedidosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque/historico': {
      id: '/estoque/historico'
      path: '/estoque/historico'
      fullPath: '/estoque/historico'
      preLoaderRoute: typeof EstoqueHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/novo': {
      id: '/categorias/novo'
      path: '/categorias/novo'
      fullPath: '/categorias/novo'
      preLoaderRoute: typeof CategoriasNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/$id/editar': {
      id: '/produtos/$id/editar'
      path: '/produtos/$id/editar'
      fullPath: '/produtos/$id/editar'
      preLoaderRoute: typeof ProdutosIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/$id/editar': {
      id: '/categorias/$id/editar'
      path: '/categorias/$id/editar'
      fullPath: '/categorias/$id/editar'
      preLoaderRoute: typeof CategoriasIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ColecaoRoute: ColecaoRoute,
  DashboardRoute: DashboardRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  TrocasEDevolucoesRoute: TrocasEDevolucoesRoute,
  CategoriasNovoRoute: CategoriasNovoRoute,
  EstoqueHistoricoRoute: EstoqueHistoricoRoute,
  PedidosIdRoute: PedidosIdRoute,
  ProdutoHandleRoute: ProdutoHandleRoute,
  ProdutosNovoRoute: ProdutosNovoRoute,
  CategoriasIndexRoute: CategoriasIndexRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  EstoqueIndexRoute: EstoqueIndexRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  PedidosIndexRoute: PedidosIndexRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
  CategoriasIdEditarRoute: CategoriasIdEditarRoute,
  ProdutosIdEditarRoute: ProdutosIdEditarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
