// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env['VITE_SUPABASE_URL'] || process.env['SUPABASE_URL'];
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] || process.env['SUPABASE_PUBLISHABLE_KEY'];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    // Loga o problema mas NÃO lança exceção — evita derrubar toda a UI
    // quando as variáveis de ambiente estão temporariamente ausentes.
    console.error(`[Supabase] Missing env var(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`);
    return null;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createClient<Database>> | null | undefined;

// Retorna o cliente Supabase ou null se as credenciais não estiverem disponíveis.
// Use `supabase` para operações normais e verifique `isSupabaseAvailable()` quando necessário.
export function isSupabaseAvailable(): boolean {
  if (_supabase === undefined) _supabase = createSupabaseClient();
  return _supabase !== null;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createClient<Database>>, {
  get(_, prop, receiver) {
    if (_supabase === undefined) _supabase = createSupabaseClient();
    // Se o cliente não pôde ser criado (credenciais ausentes), retorna
    // um stub seguro que não lança exceção — operações retornam silenciosamente.
    if (_supabase === null) {
      // Para métodos encadeados como supabase.from(...).select(...), retorna
      // um objeto que sempre resolve para { data: null, error: null }.
      const noop = (): unknown => safeStub;
      const safeStub: Record<string, unknown> = new Proxy({} as Record<string, unknown>, {
        get: () => noop,
        apply: () => Promise.resolve({ data: null, error: null }),
      });
      return noop;
    }
    return Reflect.get(_supabase, prop, receiver);
  },
});

